### PR TITLE
ci: add matrix build for Humble

### PR DESCRIPTION
**Pull request by kenji-miyake**
## Description

An improved version of #327.
I guess just adding the `branch` option is a simple solution.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by kenji-miyake** [comment]
Build CI:
- https://github.com/autowarefoundation/autoware/actions/runs/2370088810
- https://github.com/autowarefoundation/autoware/actions/runs/2370089558

**Comment by kenji-miyake** [comment]
ARM64 Humble CI failed, but it seems this PR itself works.
https://github.com/autowarefoundation/autoware/runs/6551919796?check_suite_focus=true

**Comment by kenji-miyake** [comment]
With this PR, CI will trigger with the branch of #330.
It is difficult to manage both distros in one branch.

**Review by xmfcx — APPROVED** [review]

**Comment by kenji-miyake** [comment]
I'll merge this later.

**Review by esteve — APPROVED** [review]

**Pull request merged**
