### PR TITLE
fix(repos): add the latest hash of ros/diagnostics

### PR DESCRIPTION
**Pull request by kenji-miyake**
## Description

As described in https://github.com/ros/diagnostics/issues/229, the latest code of `ros/diagnostics` isn't released yet, which includes some important bug fixes.

image

For that, I'd like to add the source dependency.

Note: I'll wait for #374 (cleanup of `autoware.repos`) to be merged.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by xmfcx — DISMISSED** [review]

**Review by esteve — DISMISSED** [review]

**Comment by kenji-miyake** [comment]
@xmfcx Could you review #374 to merge this? :pray:

**Comment by kenji-miyake** [comment]
It will be resolved for Humble (not for Galactic, which has a bug) by the next sync.
https://github.com/ros/diagnostics/issues/229#issuecomment-1152323201

**Comment by kenji-miyake** [comment]
I'm not sure if I should merge this for Galactic.
I personally think we can close this and wait for switching to Humble.
But if somebody requires this for Galactic, we can merge it.

**Comment by kenji-miyake** [comment]
I'll close this for now.

**Pull request closed without merging**
