### PR TITLE
docs: update README.md

### PR DESCRIPTION
**Pull request by kenji-miyake**
## Description

Deleted old instructions since it's added to the documentation site.

## Pre-review checklist for the PR author

PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

Reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has the write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by xmfcx — APPROVED** [review]
Looks similar to https://github.com/ros2/ros2

It's clear and on-point.

**Comment by ghost** [comment]
@kenji-miyake Will the overview information be added to the READMEs of each repository? Up-to-date documentation is important for sure, but we also need to ensure that the purpose of each repository is clear at a glance.

**Comment by kenji-miyake** [comment]
@LalithVipulananthan I think the purpose of each repository should be added to the organization profile like https://github.com/github that I believe you are working on.

And later, I can add descriptions about each repo in `.repos` as explained for Open AD Kit WG.
https://docs.google.com/presentation/d/1Y14DTQSyTlVXkAFyhVWVgf8zqDjyhL_hdpPyATOLi0w/edit#slide=id.g11a4e6b6669_0_108

**Comment by ghost** [comment]
After looking at the GitHub profile, I wasn't sure if I should do that or
not. However, that was the original plan so please allow to submit an
updated version with that information included!

**Comment by kenji-miyake** [comment]
Okay, let's discuss it at https://github.com/autowarefoundation/.github/pull/1! :smile:

**Pull request merged**
