### PR TITLE
docs: add image in readme

### PR DESCRIPTION
**Pull request by yukkysaito**
I added the same image as [here](https://github.com/tier4/AutowareArchitectureProposal.proj) because it is not attractive in the readme.

Signed-off-by: Yukihiro Saito <yukky.saito@gmail.com>

**Note**: Confirm our [contribution guidelines](https://autowarefoundation.github.io/autoware-documentation/main/contributing/) before submitting a pull request.

Click the `Preview` tab and select a PR template:

- [Standard change](?expand=1&template=standard-change.md)
- [Small change](?expand=1&template=small-change.md)

### CODE REVIEW

**Comment by kenji-miyake** [comment]
We can consider adding this to https://github.com/autowarefoundation/.github/pull/1.
I'll ask maintainers.

**Comment by kenji-miyake** [comment]
@yukkysaito https://github.com/autowarefoundation/.github/pull/1 is merged! :+1: 
https://github.com/autowarefoundation#welcome-to-the-autoware-foundation-

Will you close this? Or do you still want to add the image to this repository as well?

**Comment by yukkysaito** [comment]
@kenji-miyake :+1: I can close this PR.
I think people come to the readme of this repository, not to the AWF organization page.
So I would like to make the readme of this repository a bit more attractive.

**Comment by kenji-miyake** [comment]
@yukkysaito Yeah, it's a good idea. I'm thinking of adding more descriptions about `autoware.repos`.
Let's improve the REAMDE together in other PRs. :smile:

**Pull request closed without merging**
