### PR TITLE
feat(ansible/docker): add support for other Debian-based distros

### PR DESCRIPTION
**Pull request by esteve**
## Description

This expands support for Linux distributions based on Debian

## Pre-review checklist for the PR author

PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

Reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has the write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by esteve** [comment]
@kenji-miyake could you have a look at this PR? If you think there's someone else who I should add as reviewer, please let me know. Thanks

**Review by kenji-miyake — DISMISSED** [review]
Thank you! :smile:

**Comment by kenji-miyake** [comment]
@esteve Can I change the PR title?
- Use the present tense to follow the current style.
- Use `feat` instead of `build` and add the scope.

**Comment by kenji-miyake** [comment]
I've added a CI workflow for `setup-dev-env.sh docker`. -> Passed.

**Review by kenji-miyake — DISMISSED** [review]
I'll merge this after @esteve approves my change.

**Comment by esteve** [comment]
@kenji-miyake I updated the commit message, but unfortunately your commit got lost. Can you push it again? Sorry about that

**Comment by kenji-miyake** [comment]
@esteve No problem, it's still in my local machine! I'll push it again. :smile:

**Review by kenji-miyake — APPROVED** [review]

**Comment by esteve** [comment]
@kenji-miyake thanks!

**Pull request merged**
