### PR TITLE
feat: split simulator repos file

### PR DESCRIPTION
**Pull request by kenji-miyake**
In order to avoid the errors such as autowarefoundation/autoware.ai#2413, I'd like to split `.repos` file for simulators.
This is a tentative approach and we should discuss what is the best way to manage `.repos` files.

### CODE REVIEW

**Comment by kenji-miyake** [comment]
@hakuturu583 @vios-fish Is this okay for you?

**Comment by hakuturu583** [comment]
I think it looks nice.
I recommend to run test cases on this branch by Autoware evaluator.

**Comment by kenji-miyake** [comment]
> I recommend to run test cases on this branch by Autoware evaluator.

@hakuturu583 Yes, of course.
@vios-fish Will you set up this at a later date?

**Comment by kenji-miyake** [comment]
I'll merge this because I've opened an issue for the remaining tasks.

**Pull request merged**
