### PR TITLE
add docker support

### PR DESCRIPTION
**Pull request by xczhanjun**
Add dockerfile and docker publish action, the default user is autoware with userid=1000.

### CODE REVIEW

**Comment by kenji-miyake** [comment]
@xczhanjun Thank you, but could you open an issue before sending a pull request?
Also, as I'm sending a PR for #14, please tell me the difference, please?

**Comment by xczhanjun** [comment]
> @xczhanjun Thank you, but could you open an issue before sending a pull request? Also, as I'm sending a PR for #14, please tell me the difference, please?

Wow, thanks, you are developing  this future, let me try.

**Comment by xczhanjun** [comment]
> > @xczhanjun Thank you, but could you open an issue before sending a pull request? Also, as I'm sending a PR for #14, please tell me the difference, please?
> 
> Wow, thanks, you are developing this future, let me try.

I will try your future and the docker image in my forked repo.

**Comment by kenji-miyake** [comment]
I'll prepare official contributing guidelines [here](https://github.com/autowarefoundation/autoware-documentation/issues/6), but generally speaking, it's better to discuss things on issues before opening a PR.

So let me close this for now. :bow: 
Please re-open this after discussions on issues and if this PR is necessary.

**Pull request closed without merging**
