### PR TITLE
feat: add autoware_launch to autoware.repos

### PR DESCRIPTION
**Pull request by kenji-miyake**
While I'm writing this tutorial https://github.com/autowarefoundation/autoware-documentation/pull/28, I found that we have to run Autoware by `ros2 launch tier4_autoware_launch`.

However, it's not a good interface because the CLI interface will change depending on the launch package.
It's useful if all users can use the same interface `ros2 launch autoware_launch`.

The followings are the images of the As-is and the To-be state.

As-is: We can't use the same package name, so the CLI interface will change.

```mermaid
graph TD
    User -->|ros2 launch another_autoware_launch| another_autoware_launch
    User -->|ros2 launch tier4_autoware_launch| tier4_autoware_launch

    another_autoware_launch --> company_A_sensing_launch_1
    another_autoware_launch --> company_B_perception_launch_1
    another_autoware_launch --> company_C_planning_launch_1

    tier4_autoware_launch --> tier4_sensing_launch
    tier4_autoware_launch --> tier4_perception_launch
    tier4_autoware_launch --> company_C_planning_launch_1

    subgraph autowarefoundation/autoware.universe
        another_autoware_launch
        tier4_autoware_launch
        company_A_sensing_launch_1
        company_B_perception_launch_1
        company_C_planning_launch_1
    end

    subgraph tier4/tier4_sensor_kit_launch
        tier4_sensing_launch
        tier4_perception_launch
    end
```

Note: We can't use the name autoware_launch here because the package names will conflict.

To-be: We can use the same package name, so we can use the same CLI interface.

```mermaid
graph TD
    User -->|ros2 launch autoware_launch| autoware_launch_1
    User -->|ros2 launch autoware_launch| autoware_launch_2

    autoware_launch_1 --> company_A_sensing_launch_1
    autoware_launch_1 --> company_B_perception_launch_1
    autoware_launch_1 --> company_C_planning_launch_1

    autoware_launch_2 --> tier4_sensing_launch
    autoware_launch_2 --> tier4_perception_launch
    autoware_launch_2 --> company_C_planning_launch_1

    subgraph autowarefoundation/autoware_launch
        autoware_launch_1
    end

    subgraph tier4/autoware_launch
        autoware_launch_2
    end


    subgraph autowarefoundation/autoware.universe
        company_A_sensing_launch_1
        company_B_perception_launch_1
        company_C_planning_launch_1
    end

    subgraph tier4/tier4_sensor_kit_launch
        tier4_sensing_launch
        tier4_perception_launch
    end
```

Therefore, I'd like to add the autoware_launch repository to `autoware.repos`.
We can switch the implementation of autoware_launch by changing the reference in `autoware.repos`.

Note: Of course, if users want to use a name other than `autoware_launch`, they can use it. This PR will just add an option for users.

### CODE REVIEW

**Comment by kenji-miyake** [comment]
@mitsudome-r @xmfcx @yukkysaito Could you review this, please? :pray: 
Any comments/questions are welcome!

**Comment by kenji-miyake** [comment]
Related to this, I'll move `tier4_autoware_launch` package from https://github.com/tier4/autoware.universe to https://github.com/tier4/autoware_launch and rename the package name to `autoware_launch`.

-> 
- https://github.com/autowarefoundation/autoware_launch/pull/1
- https://github.com/autowarefoundation/autoware.universe/pull/420

**Comment by xmfcx** [comment]
If we go with the 2nd option (your proposal), What happens if 2 launch files under different companies have the same names?

Example:
- `company_A_sensing_launch_1.launch.py`
- `tier4_sensing_launch.launch.py`
These could have the same name.

Are we going to enforce all launch files to have the same prefix?

Can we enforce/check it automatically?

**Comment by kenji-miyake** [comment]
@xmfcx If the package names are the same, it can be detected in `rosdep install` or `colcon build`. Avoiding conflicts of package names is the responsibility of the maintainer of `autoware.repos`.

If the package names are different, they can have the same launch file name, but the CLI interface will change.

```
ros2 launch autoware_launch autoware.launch # The main launch is `autoware_launch`. (recommended, but not necessary)
ros2 launch company_A_autoware_launch autoware.launch # We can have additional launch packages in different package names
```

Is it clear?

**Comment by xmfcx** [comment]
```mermaid
graph TD
    User -->|ros2 launch autoware_launch| autoware_launch_1
    User -->|ros2 launch autoware_launch| autoware_launch_2

    autoware_launch_1 --> company_A_sensing_launch_1
    autoware_launch_1 --> company_B_perception_launch_1
    autoware_launch_1 --> company_C_planning_launch_1

    autoware_launch_2 --> tier4_sensing_launch
    autoware_launch_2 --> tier4_perception_launch
    autoware_launch_2 --> company_C_planning_launch_1

    subgraph autowarefoundation/autoware_launch
        autoware_launch_1
    end

    subgraph tier4/autoware_launch
        autoware_launch_2
    end


    subgraph autowarefoundation/autoware.universe
        company_A_sensing_launch_1
        company_B_perception_launch_1
        company_C_planning_launch_1
    end

    subgraph tier4/tier4_sensor_kit_launch
        tier4_sensing_launch
        tier4_perception_launch
    end
```

Here, are `autoware_launch_1` and `autoware_launch_2` packages or just folders?

**Comment by kenji-miyake** [comment]
@xmfcx They are packages, but I should have named both of them `autoware_launch`.
(I simply added suffixes to avoid conflicts in Mermaid IDs.)

**Comment by xmfcx** [comment]
@kenji-miyake I understood now.

You are proposing for different organizations to have their fork of `autoware_launch` to keep the same name.

They can modify it and it is their responsibility to source the correct ros2 workspace. But they shouldn't change the package name.

I am ok with this change.

**Comment by kenji-miyake** [comment]
@xmfcx Yes, exactly! Thank you, I'll merge this. :smile: 

> But they shouldn't change the package name.

Yeah, actually they can, but it's not recommended if they want to use the same CLI of `ros2 launch autoware_launch`.

**Pull request merged**
