### PR TITLE
ci: add github-release.yaml

### PR DESCRIPTION
**Pull request by kenji-miyake**
## Description

It's useful if we can prepare releases after pushing a tag.
I'd like to add this workflow to all Autoware repositories.

It's already used and tested in `autoware-github-actions`.
https://github.com/autowarefoundation/autoware-github-actions/releases

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by kenji-miyake** [comment]
After this is approved, I'll update the sync-files settings in each repository.

**Comment by kenji-miyake** [comment]
I've added `inputs` for `workflow_dispatch` and tested it in my fork.
https://github.com/kenji-miyake/autoware-github-actions/releases

**Review by esteve — DISMISSED** [review]
@kenji-miyake thanks, very useful!

**Comment by kenji-miyake** [comment]
@esteve Thank you for your review!
As I'm thinking of supporting `beta/vX.Y.Z` branches, I'll push some code later. Please re-review then. :bow:

**Comment by kenji-miyake** [comment]
Tested like this.

image

image

**Review by esteve — APPROVED** [review]

**Pull request merged**
